[package]
name = "shapes"
version = "0.1.0"
edition = "2021"

[dependencies]
tetrominos = { path = "../tetrominos" }
orientation = { path = "../orientation" }
strum = "0.26.3"
lazy_static = "1.5.0"
colored = "3.0.0"
